include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - test

.uenv_image:
  stage: test
  image: arbor/v0.9:latest
  variables:
    UENV_VIEW: 'develop'

.test_unit:
  extends: .uenv_image
  script:
    - cd /arbor.src
    - build/bin/unit-modcc
    - build/bin/unit-local
    - build/bin/unit
    - scripts/run_cpp_examples.sh
    - python -m venv --system-site-packages /arbor.install
    - source /arbor.install/bin/activate
    - python -m unittest discover -v -s python
    - scripts/run_python_examples.sh
    - scripts/test_executables.sh
    - deactivate
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_NTASKS_PER_NODE: 1
    SLURM_TIMELIMIT: "00:30:00"
    SLURM_CPU_BIND: "verbose,none"
    USE_MPI: "NO"

#test_x86_64:
#  extends: [.uenv-runner-eiger-mc, .test_unit]
#  variables:
#    SLURM_CONSTRAINT: mc

test_aarch64:
  extends: [.uenv-runner-todi-gh200, .test_unit]
  variables:
    SLURM_ACCOUNT: g154
    SLURM_RESERVATION: daint

.test_distributed:
  extends: .uenv_image
  script:
    - cd /arbor.src
    - build/bin/unit-mpi
    - scripts/run_cpp_examples.sh -d
  variables:
    SLURM_JOB_NUM_NODES: 2
    SLURM_CPU_BIND: "verbose,rank_ldom"
    SLURM_TIMELIMIT: "00:30:00"
    USE_MPI: "YES"

#test_x86_64-distributed:
#  extends: [.uenv-runner-eiger-mc, .test_distributed]
#  variables:
#    SLURM_CONSTRAINT: mc
#    SLURM_NTASKS_PER_NODE: 8

test_aarch64-distributed:
  extends: [.uenv-runner-todi-gh200, .test_distributed]
  variables:
    SLURM_GPUS_PER_NODE: 4
    SLURM_GPUS_PER_TASK: 1
    SLURM_NTASKS_PER_NODE: 4
