# Order of inclusion matters below:
# 1. include the remote ci-ext.yaml
# 2. include common.yaml
# 3. include architecture specific configurations
include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'
  - local: '.gitlab/includes/common.yaml'
  - local: '.gitlab/includes/gh200.yaml'
  - local: '.gitlab/includes/epic7742.yaml'

stages:
  - build
  - test
