#!/usr/bin/env bash

if gitlog=$(git log -1 --pretty=format:'%cI %H' 2>/dev/null); then
    git diff --quiet HEAD 2>/dev/null || gitlog="${gitlog} modified"
else
    gitlog='unknown commit'
fi

echo "$gitlog"
