#pragma once

#include <arbor/cable_cell_param.hpp>
#include <arbor/common_types.hpp>
#include <arbor/export.hpp>

#include <array>
#include <cstdint>
#include <functional>
#include <memory>
#include <optional>
#include <ostream>
#include <stdexcept>
#include <tuple>
#include <utility>
#include <vector>

namespace arb {

using network_location = std::array<double, 3>;

using network_hash_type = std::uint64_t;

struct network_site_info {
    cell_gid_type gid;
    cell_kind kind;
    const cell_tag_type& tag;
    const network_location& location;
    network_hash_type hash;
};

struct network_selection_impl;

class ARB_SYMBOL_VISIBLE network_selection {
public:
    network_selection() { *this = network_selection::all(); }

    // Select all
    static network_selection all();

    // Select none
    static network_selection none();

    static network_selection source_cell_kind(cell_kind kind);

    static network_selection destination_cell_kind(cell_kind kind);

    static network_selection source_label(std::vector<cell_tag_type> labels);

    static network_selection destination_label(std::vector<cell_tag_type> labels);

    static network_selection source_gid(std::vector<cell_gid_type> gids);

    static network_selection destination_gid(std::vector<cell_gid_type> gids);

    // Invert the selection
    static network_selection invert(network_selection s);

    // Only select connections between different cells
    static network_selection inter_cell();

    // Only select connections when the global labels are not equal. May select intra-cell
    // connections, if the local label is not equal.
    static network_selection not_equal();

    // Random selection using the bernoulli random distribution with probability "p" between 0.0
    // and 1.0
    static network_selection bernoulli_random(unsigned seed, double p);

    // Custom selection using the provided function "func". Repeated calls with the same arguments
    // to "func" must yield the same result. For gap junction selection,
    // "func" must be symmetric (func(a,b) = func(b,a)).
    static network_selection custom(
        std::function<bool(const network_site_info& src, const network_site_info& dest)> func);

    // only select within given distance. This may enable more efficient sampling through an
    // internal spatial data structure.
    static network_selection within_distance(double distance);

    // random bernoulli sampling with a linear interpolated probabilty based on distance. Returns
    // "false" for any distance outside of the interval [distance_begin, distance_end].
    static network_selection linear_bernoulli_random(unsigned seed,
        double distance_begin,
        double p_begin,
        double distance_end,
        double p_end);

    network_selection operator&(network_selection right) const;

    network_selection operator|(network_selection right) const;

    network_selection operator^(network_selection right) const;

private:
    std::shared_ptr<network_selection_impl> impl_;
};

class ARB_SYMBOL_VISIBLE network_value {
public:
    // Uniform value
    network_value(double value);

    // Uniform value. Will always return the same value given at construction.
    static network_value uniform(double value);

    // Uniform random value in (range[0], range[1]]. Always returns the same value for repeated
    // calls with the same arguments and calls are symmetric v(a, b) = v(b, a).
    static network_value uniform_distribution(unsigned seed, const std::array<double, 2>& range);

    // Radom value from a normal distribution with given mean and standard deviation. Always returns
    // the same value for repeated calls with the same arguments and calls are symmetric v(a, b) =
    // v(b, a).
    static network_value normal_distribution(unsigned seed, double mean, double std_deviation);

    // Radom value from a truncated normal distribution with given mean and standard deviation (of a
    // non-truncated normal distribution), where the value is always in (range[0], range[1]]. Always
    // returns the same value for repeated calls with the same arguments and calls are symmetric
    // v(a, b) = v(b, a). Note: Values are generated by reject-accept method from a normal
    // distribution. Low acceptance rate can leed to poor performance, for example with very small
    // ranges or a mean far outside the range.
    static network_value truncated_normal_distribution(unsigned seed,
        double mean,
        double std_deviation,
        const std::array<double, 2>& range);

    // Custom value using the provided function "func". Repeated calls with the same arguments
    // to "func" must yield the same result. For gap junction values,
    // "func" must be symmetric (func(a,b) = func(b,a)).
    static network_value custom(std::function<double(const cell_global_label_type&,
            const network_location&,
            const cell_global_label_type&,
            const network_location&,
            double)> func);

    // inline double operator()(cell_gid_type src_gid,
    //     const network_location& global_src_location,
    //     network_hash_type src_hash,
    //     cell_gid_type dest_gid,
    //     const network_location& global_dest_location,
    //     network_hash_type dest_hash) const {
    //     return impl_->get(
    //         src_gid, global_src_location, src_hash, dest_gid, global_dest_location, dest_hash);
    // }

private:

    struct value_impl {
        // virtual double get(cell_gid_type src_gid,
        // const network_location& global_src_location,
        // network_hash_type src_hash,
        // cell_gid_type dest_gid,
        // const network_location& global_dest_location,
        // network_hash_type dest_hash) const = 0;

        virtual ~value_impl() = default;
    };

    struct uniform_distribution_impl;
    struct normal_distribution_impl;
    struct truncated_normal_distribution_impl;
    struct custom_impl;
    struct uniform_impl;

    network_value(std::shared_ptr<value_impl> impl);

    // inline double get(cell_gid_type src_gid,
    //     const network_location& global_src_location,
    //     network_hash_type src_hash,
    //     cell_gid_type dest_gid,
    //     const network_location& global_dest_location,
    //     network_hash_type dest_hash) const {
    //     return impl_->get(
    //         src_gid, global_src_location, src_hash, dest_gid, global_dest_location, dest_hash);
    // }

    std::shared_ptr<value_impl> impl_;
};

struct network_description {
    network_selection selection;
    network_value weight;
    network_value delay;
};

}  // namespace arb
